apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo
  labels:
    app: todo-api
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: ghcr.io/kebien6020/todo-kubernetes:master
          env:
            - name: PG_CONNECTION_STRING
              value: postgresql://postgres:secret@todo-pg/postgres
          ports:
            - name: http
              containerPort: 4300
              protocol: TCP
